[package]
name = "TODO_change"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.13.0", features = ["full"] }
dotenv = "0.15.0"
eyre = "0.6.12"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
